### ISSUE TITLE
Convert from Int64 to number

### ISSUE THREAD

**Issue by walter-konnerth** [peheje/JsonSerializerSwift#10]
Can you please update the code so Int64 is treated as number, not as a string?

**Comment by peheje** [comment]
Thanks for the bug report. Try pull. Please verify if it fixes the issue.

**Comment by walter-konnerth** [comment]
Thank you!

That did the trick!

Regards / Cu stima,

Walter KONNERTH

Project Manager

QUALTEH ROMANIA

walter.konnerth@qualteh.ro
Mobil: +4 0752 222 210

Timisoara, 300210
Str. Anisoara Odeanu, Nr. 22
Telefon: +4 0356 881 933
Fax: +4 0356 881 934
www.qualteh.ro
