### ISSUE TITLE
Missing Dependency Manager

### ISSUE THREAD

**Issue by svas-datalicious** [peheje/JsonSerializerSwift#11]
Hi @peheje It would be great of you if you host this on the Dependency Managing Tools. Since everyone in the industry tries to keep the third party lib as dependencies. So, hosting it in Cocoa Pods, Carthage should suffice.

**Comment by peheje** [comment]
Thanks for the suggestion. I will definitely take a look at it at some point. I'm very busy with exams atm. though.

**Comment by iOSUKDev** [comment]
Hi @peheje How to use JsonSerializerSwift into the project, just copying the files or the framework? as I am having issues in complying the framework now.

**Comment by munirwanis** [comment]
Just paste the swift file on your project.

**Comment by elisechant** [comment]
But how?

**Comment by peheje** [comment]
Three years have passed. There are now better and more reliable built-in ways to serialize json. Look up Codable.

Choose again.
