### ISSUE TITLE
Getting \ in .toJson() result

### ISSUE THREAD

**Issue by nissaba** [peheje/JsonSerializerSwift#3]
hello. I tested this class and I got some odd results. 
I tested using a class to transform it to a json string then get the dictionary for it. 

so lets say:

```
class Cat {
 var name: String?
 var color: String?
 var age: String?
 var location: Location
}

struct Location{
 var latitude: Int
 var longitude: Int
}

let cat = Cat()
cat.name = "Mr. Cat"
cat.color = "Orange"
cat.age = "3"
cat.location.longitude = 29.393
cat.location.latitude = -75.762523

let jsonString = JSONSerializer.toJson(cat)

print(jsonString)
```

the output is :
`{"name":"Mr. Cat", "color":"Orange", "age":"3", "location":appName.Location(latitude: 29.393, longitude: -75.762523)}`

I dont know why the var location is printed this why just because its a struct or a embeded class.

**Comment by peheje** [comment]
Thank you for your interest.
I have not made support for structs yet. That is an omission. I might take
a look at it. You are of course also welcome. Thank you.

If you change the location to a class it should work.

**Comment by peheje** [comment]
I have updated the Serializer to take care of structs. Please pull and test if it works for you now :-)

**Comment by nissaba** [comment]
Changing the struct to a class gave this result: 
 {"name":"Mr. Cat", "color":"Orange", "age":"3", "location":appName.Location}

and as for struct no change. as long as the variables/properties are set to optional. 

but it work for : 

```
class Cat {
  var name: String?
  var color: String?
  var age: String?
  var location: Location!
 }
```

also in the case that location is optional and that latitude and longitude are also optional I see it print the values of latitude and longitude as  ... "longitude":optional(29.393) ...

**Comment by peheje** [comment]
I'm not sure how your code is building.
1. The types of your Location are integers, but you try to assign double values to them.
2. You never initialize your location object so you can't assign values to location.longitude or location.latitude.

Try the following:
    func test_cat() {

```
    //1. Define location struct before usages
    struct Location{
        //2. Assign values or use init(){}
        var latitude: Double = 0    //3. use double type
        var longitude: Double = 0
    }

    class Cat {
        var name: String?
        var color: String?
        var age: String?
        //4. call the constructor for the location object to construct it or use init(){}
        var location: Location = Location()
    }

    let cat = Cat()
    cat.name = "Mr. Cat"
    cat.color = "Orange"
    cat.age = "3"
    cat.location.longitude = 29.393
    cat.location.latitude = -75.762523

    let jsonString = JSONSerializer.toJson(cat)

    print(jsonString)
}
```

**Comment by nissaba** [comment]
The code I am testing with is work related and I can not share it, so I created a simplified interpretation of it. but yes I should have set the values as doubles or float in the example. 

errata :  for now working code

```
class Cat {
  var name: String?
  var color: String?
  var age: String?
  var location: Location!
  init()
  {
     location = Location(latitude: -75.762523, longitude: 29.393)
  }
 }

 struct Location{
  var latitude: Double?
  var longitude: Double?
 }
```

**Comment by nissaba** [comment]
Made this playground to get the "optional(value)" to print out in the json string

"{"name": "Mr. Cat", "color": "Orange", "age": "3", "location": Location(latitude: Optional(-75.762523000000002), longitude: Optional(29.393000000000001))}"

if location is set to non optional then it prints good 

```
//: Playground - noun: a place where people can play

import UIKit

import Foundation
import JsonSerializerSwift

class Cat {
    var name: String?
    var color: String?
    var age: String?
    var location: Location?
    init()
    {
        location = Location(latitude: -75.762523, longitude: 29.393)
    }
}

struct Location{
    var latitude: Double?
    var longitude: Double?
}

let cat = Cat()
cat.name = "Mr. Cat"
cat.color = "Orange"
cat.age = "3"

let jsonString = JSONSerializer.toJson(cat)

print(jsonString)
```

**Comment by peheje** [comment]
Currently have an issue with optional doubles. But the optional part should
be unwrapped. Are you sure you have the latest commit. I updated yesterday.

**Comment by nissaba** [comment]
yes I downloaded it this morning. :) Since I am using this to transform a class, that is a model for a alamofire request to a rest-service , I will need to generate all encapsulated struct/class that make the JSon request object. So setting them as non-optional works for me in any case for now. 

and by the way! great job :) I have looked far and wide from some thing simple that I do not have to hack my models or extend them and so on to be able to transform them from a struct or class to a json dictionary.  So most likely this will be added to the next version of Prospects / MLS-Touch in the next version of the software. :)

**Comment by peheje** [comment]
Thank you very much.
I'm glad I can give a little back to the community that has given me so
much :-)

I tried to update the code to handle optional structs. Feedback much
appreciated.

On 7 June 2016 at 17:28, Pascale Beaulac notifications@github.com wrote:

> yes I downloaded it this morning. :) Since I am using this to transform a
> class, that is a model for a alamofire request to a rest-service , I will
> need to generate all encapsulated struct/class that make the JSon request
> object. So setting them as non-optional works for me in any case for now.
> 
> and by the way! great job :) I have looked far and wide from some thing
> simple that I do not have to hack my models or extend them and so on to be
> able to transform them from a struct or class to a json dictionary. So most
> likely this will be added to the next version of Prospects / MLS-Touch in
> the next version of the software. :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/peheje/JsonSerializerSwift/issues/3#issuecomment-224317581,
> or mute the thread
> https://github.com/notifications/unsubscribe/AG77lvnQ2tVM-r0L3uf4d2Pt_2qY9qveks5qJY42gaJpZM4IvUoI
> .

## 

Mvh. Peter H. Jensen
