### ISSUE TITLE
Suggestion : add json styler/pretifier function too.

### ISSUE THREAD

**Issue by ViliusJanulis** [peheje/JsonSerializerSwift#5]
```
//1. convert string to NSData
let jsonData = json.dataUsingEncoding(NSUTF8StringEncoding)!

//2. convert JSON data to JSON object
let jsonObject:AnyObject = try! NSJSONSerialization.JSONObjectWithData(jsonData, options: [])

//3. convert back to JSON data by setting .PrettyPrinted option
let prettyJsonData = try! NSJSONSerialization.dataWithJSONObject(jsonObject, options: .PrettyPrinted)

//4. convert NSData back to NSString (use NSString init for convenience), later you can convert to String.
let prettyPrintedJson = NSString(data: prettyJsonData, encoding: NSUTF8StringEncoding)!

return prettyPrintedJson as String
```

**Comment by peheje** [comment]
Thanks. Try out the new commit.

On 22 June 2016 at 18:28, Vilius Janulis notifications@github.com wrote:

> //1. convert string to NSData
> let jsonData = json.dataUsingEncoding(NSUTF8StringEncoding)!
> 
> //2. convert JSON data to JSON object
> let jsonObject:AnyObject = try! NSJSONSerialization.JSONObjectWithData(jsonData, options: [])
> 
> //3. convert back to JSON data by setting .PrettyPrinted option
> let prettyJsonData = try! NSJSONSerialization.dataWithJSONObject(jsonObject, options: .PrettyPrinted)
> 
> //4. convert NSData back to NSString (use NSString init for convenience), later you can convert to String.
> let prettyPrintedJson = NSString(data: prettyJsonData, encoding: NSUTF8StringEncoding)!
> 
> return prettyPrintedJson as String
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/peheje/JsonSerializerSwift/issues/5, or mute the
> thread
> https://github.com/notifications/unsubscribe/AG77lvGRIJJMtc8W_5hm4kpGxF6v7X72ks5qOWKqgaJpZM4I7-QD
> .

## 

Mvh. Peter H. Jensen
